config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  root 'home#index'

  get '/about' => 'home#about'

  post '/questions' => 'home#temp'
  
  post '/answers' => 'home#temp'

  get '/questions/:id' => 'home#question'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    include HasGravatar
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_gravatar.rb
module HasGravatar
    def gravatar
        "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
    end
end

app/models/question.rb
class Question < ApplicationRecord
    include HasGravatar
    has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def create
        question = Question.find(params[:answer][:question_id])
        answer = question.answers.create(answer_params)
        MainMailer.notify_question_author(answer).deliver_later
        session[:current_email_user] = answer_params[:email]
        redirect_to question
    end

    private 

    def answer_params
        params.require(:answer).permit(:email, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc).all
  end

  def about
  end

  def temp
    redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def show
        @question = Question.find(params[:id])
        @answers = @question.answers.order(created_at: :desc)
    end

    def create
        Question.create(question_params)
        session[:current_email_user] = question_params[:email]
        redirect_to root_path
    end

    private

    def question_params
        params.require(:question).permit(:email, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_email_user
        session[:current_email_user]
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
    <a href="/" class="navbar-brand">History of the Universe</a>
    <form class="form-inline">
        <div class="navbar-text">
            <%= current_email_user %>
        </div>
        <button class="btn btn-outline-success my-2 my-sm-0" type="button" data-toggle="modal" data-target="#new-question-modal">Ask Question</button>
    </form>
</nav>

app/views/home/_new_answer_form.html.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Answer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span> 
                </button>
            </div>
            <%= form_for :answer, url: '/answers', html: { class: 'form_horizontal' } do %>
                <input type="hidden" name="answer[question_id]" value="<%= @question.id %>" />
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" name="answer[email]" value="<%= current_email_user %>" class="form-control" id="inputEmail3" placeholder="Email" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputAnswer3" class="col-sm-2 col-form-label">Answer</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="answer[body]" id="inputAnswer3" placeholder="What is your answer?" required></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New Question</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <%= form_for :question, url: '/questions', html: { class: 'form_horizontal' } do %>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                        <div class="col-sm-10">
                            <input type="email" name="question[email]" value="<%= current_email_user %>" class="form-control" id="inputEmail3" placeholder="Email" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputQuestion3" class="col-sm-2 col-form-label">Question</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" name="question[body]" id="inputQuestion3" placeholder="What would you like to know" required></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<div class="container">
    <div class="well card">
        <h2>The universe is the totality of everything that exists, has existed, or will exist.</h2>
        <h3>This Q&A site is dedicated to questions about the history of the universe.</h3>
    </div>
    <div class="container">
        <div class="boxes">
            <% @questions.each do |q| %>
                <div class="media" data-target="<%= question_path(q) %>">
                    <img src="<%= q.gravatar %>" class="mr-3" alt="...">
                    <div class="media-body">
                        <h5 class="mt-0"><%= q.email %> asked:</h5>
                        <div class="time hidden-xs">
                            <%= time_ago_in_words q.created_at %> ago
                        </div>
                        <%= truncate q.body, length: 300 %>
                        <div>
                            <a href="<%= question_path(q) %>" class="btn btn-success btn-xs">View Answers</a>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>

        <% if @questions.empty? %>
            <div class="alert alert-info">
                Nothing here yet, be the first to ask?
            </div>
        <% end %>
    </div>
</div>

app/views/home/question.html.erb
<div class="container">
    <div class="lead card">
        <div class="media">
            <img src="http://www.gravatar.com/avatar/424242"  class="mr-3" alt="...">
            <div class="media-body">
                <h5 class="mt-0">user@email.com asked:</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
    </div>
    <div>
        <div>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
        </div>
        <%= render 'home/new_answer_form' %>
        <div class="media">
            <img src="http://www.gravatar.com/avatar/424242" class="mr-3" alt="...">
            <div class="media-body">
                <h5 class="mt-0">user@email.com answered:</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
        <div class="media">
            <img src="http://www.gravatar.com/avatar/424242" class="mr-3" alt="...">
            <div class="media-body">
                <h5 class="mt-0">user@email.com answered:</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
        <div class="media">
            <img src="http://www.gravatar.com/avatar/424242" class="mr-3" alt="...">
            <div class="media-body">
                <h5 class="mt-0">user@email.com answered:</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
        </div>
    </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>History of the Universe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>

      <%= render 'home/navbar' %>

      <%= yield %>

      <%= render 'home/new_question_form' %>
    
  </body>
</html>

app/views/questions/show.html.erb
<div class="container">
    <div class="lead card">
        <div class="media">
            <img src="<%= @question.gravatar %>"  class="mr-3" alt="...">
            <div class="media-body">
                <h5 class="mt-0"><%= @question.email %> asked:</h5>
                <%= @question.body %>
            </div>
        </div>
    </div>
    <div>
        <div>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
        </div>
        <%= render 'home/new_answer_form' %>
        <% @answers.each do |answer| %>
            <div class="media">
                <img src="<%=  answer.gravatar %>" class="mr-3" alt="...">
                <div class="media-body">
                    <h5 class="mt-0"><%= answer.email %> answered:</h5>
                    <div>
                        <%= time_ago_in_words answer.created_at %> ago
                    </div>
                    <%= answer.body %>
                </div>
            </div>   
        <% end %>    
        <% if @answers.empty? %>
            <div class="alert alert-info">
                Nothing here yet, be the first to answer?
            </div>
        <% end %>
    </div>  
</div>